server:
  port: :3000
  devMode: debug #release or debug
  appName: 金科
  jwtKey: k8sgolangapp
  tokenExp: 1

database:
  host: mysql.default
  port: 3306
  name: longhorn
  user: root
  password: rancher
  
log:
  fileName: app.log
  filePath: ./log